# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 13:52
from __future__ import unicode_literals

from django.db import migrations

from saleor.product.models import Category, Product


def init_data(apps, schema_editor):
    category = init_categories(apps, schema_editor)
    init_products(apps, schema_editor, category)


def init_categories(app, schema_editor):
    engine_oils = Category(name="Engine oils", description="Engine oils", hidden=False, slug="engine-oils")
    engine_oils.save()

    oil_0w40 = Category(name="0w40", description="Engine oils with grader 0w40", hidden=False, slug="0w40",
                        parent=engine_oils)
    oil_0w40.save()

    transmission_oils = Category(name="Transmission oils", description="Transmission oils", hidden=False,
                                 slug="transmission-oils")
    transmission_oils.save()

    brake_fluid = Category(name="Brake fluid", description="brake_fluid", hidden=False,
                           slug="brake-fluid")
    brake_fluid.save()

    return oil_0w40


def init_products(app, schema_editor, category):
    amsoil_signature_5w30 = Product(name="Amsoil 5W-30 Signature Series Full Synthetic Motor Oil", weight=0.946,
                                    price=28, description='''AMSOIL Signature Series Synthetic Motor Oil is engineered to
                                                outperform conventional and synthetic motor oils. It combines
                                                industry-premier synthetic technology with AMSOIL premium additives
                                                in a unique formulation that exceeds the higher performance demands
                                                of modern engines. Signature Series delivers the performance and value
                                                upon which the AMSOIL reputation is built. The culmination of more than
                                                 40 years of expertise, its exclusive formulation raises the bar for
                                                  motor oil performance.''')
    amsoil_signature_5w30.save()
    amsoil_signature_5w30.categories.add(category)


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0012_auto_20160218_0812'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
