# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-31 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20160731_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_us',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bg',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en_us',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
    ]
