# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20160731_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name_bg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='variant name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_en_us',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='variant name'),
        ),
    ]
