# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-31 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20160731_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sku_bg',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku_en_us',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
