# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20160731_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='sku_en_us',
            new_name='sku_en',
        ),
    ]
