# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20160922_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=10000),
        ),
    ]
