# Generated by Django 2.2 on 2019-05-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0004_partbrand_logo_picture'),
        ('product', '0092_auto_20190501_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='art_code_1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='art_code_2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='autoparts.PartBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_art_code_1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
