# Generated by Django 2.2 on 2019-05-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_auto_20190506_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_autopart',
            field=models.BooleanField(default=False),
        ),
    ]
