# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethodCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('region_en', models.CharField(max_length=255)),
                ('village_or_city', models.CharField(max_length=2)),
                ('update_time', models.DateTimeField(max_length=255)),
            ],
        ),
        migrations.AlterModelManagers(
            name='shippingmethodcountry',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='country_code',
            field=models.CharField(blank=True, choices=[('', 'Any country'), ('GW', 'Guinea-Bissau'), ('SN', 'Senegal'), ('AW', 'Aruba'), ('GR', 'Greece'), ('PW', 'Palau'), ('LT', 'Lithuania'), ('PM', 'Saint Pierre and Miquelon'), ('TN', 'Tunisia'), ('SK', 'Slovakia'), ('AZ', 'Azerbaijan'), ('RE', 'Réunion'), ('HK', 'Hong Kong'), ('MX', 'Mexico'), ('SL', 'Sierra Leone'), ('AS', 'American Samoa'), ('HU', 'Hungary'), ('BS', 'Bahamas'), ('CD', 'Congo (the Democratic Republic of the)'), ('CX', 'Christmas Island'), ('ET', 'Ethiopia'), ('LS', 'Lesotho'), ('IQ', 'Iraq'), ('CZ', 'Czech Republic'), ('NC', 'New Caledonia'), ('DK', 'Denmark'), ('VC', 'Saint Vincent and the Grenadines'), ('PE', 'Peru'), ('NZ', 'New Zealand'), ('JO', 'Jordan'), ('BT', 'Bhutan'), ('NO', 'Norway'), ('FM', 'Micronesia (Federated States of)'), ('GB', 'United Kingdom of Great Britain and Northern Ireland'), ('VN', 'Viet Nam'), ('EG', 'Egypt'), ('BF', 'Burkina Faso'), ('GQ', 'Equatorial Guinea'), ('HN', 'Honduras'), ('GG', 'Guernsey'), ('MR', 'Mauritania'), ('RW', 'Rwanda'), ('BR', 'Brazil'), ('SJ', 'Svalbard and Jan Mayen'), ('LY', 'Libya'), ('TF', 'French Southern Territories'), ('TH', 'Thailand'), ('KW', 'Kuwait'), ('UM', 'United States Minor Outlying Islands'), ('JP', 'Japan'), ('CY', 'Cyprus'), ('BW', 'Botswana'), ('BZ', 'Belize'), ('SC', 'Seychelles'), ('PF', 'French Polynesia'), ('AE', 'United Arab Emirates'), ('MF', 'Saint Martin (French part)'), ('IO', 'British Indian Ocean Territory'), ('CI', "Côte d'Ivoire"), ('DM', 'Dominica'), ('LI', 'Liechtenstein'), ('KG', 'Kyrgyzstan'), ('TZ', 'Tanzania, United Republic of'), ('ZW', 'Zimbabwe'), ('CN', 'China'), ('WS', 'Samoa'), ('IL', 'Israel'), ('SV', 'El Salvador'), ('AM', 'Armenia'), ('DE', 'Germany'), ('PR', 'Puerto Rico'), ('MM', 'Myanmar'), ('MD', 'Moldova (the Republic of)'), ('GE', 'Georgia'), ('GT', 'Guatemala'), ('LB', 'Lebanon'), ('CA', 'Canada'), ('UG', 'Uganda'), ('VI', 'Virgin Islands (U.S.)'), ('ZA', 'South Africa'), ('ST', 'Sao Tome and Principe'), ('MT', 'Malta'), ('KR', 'Korea (the Republic of)'), ('GL', 'Greenland'), ('TJ', 'Tajikistan'), ('NI', 'Nicaragua'), ('SO', 'Somalia'), ('FI', 'Finland'), ('GY', 'Guyana'), ('ME', 'Montenegro'), ('MP', 'Northern Mariana Islands'), ('IT', 'Italy'), ('KP', "Korea (the Democratic People's Republic of)"), ('ID', 'Indonesia'), ('LC', 'Saint Lucia'), ('NE', 'Niger'), ('FJ', 'Fiji'), ('GM', 'Gambia'), ('MK', 'Macedonia (the former Yugoslav Republic of)'), ('AL', 'Albania'), ('AD', 'Andorra'), ('YE', 'Yemen'), ('CR', 'Costa Rica'), ('TL', 'Timor-Leste'), ('RO', 'Romania'), ('JE', 'Jersey'), ('AO', 'Angola'), ('SM', 'San Marino'), ('SG', 'Singapore'), ('CM', 'Cameroon'), ('BY', 'Belarus'), ('PS', 'Palestine, State of'), ('EH', 'Western Sahara'), ('BV', 'Bouvet Island'), ('CC', 'Cocos (Keeling) Islands'), ('MU', 'Mauritius'), ('CO', 'Colombia'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('MS', 'Montserrat'), ('SZ', 'Swaziland'), ('TT', 'Trinidad and Tobago'), ('CV', 'Cabo Verde'), ('ES', 'Spain'), ('BH', 'Bahrain'), ('GD', 'Grenada'), ('BO', 'Bolivia (Plurinational State of)'), ('HM', 'Heard Island and McDonald Islands'), ('NU', 'Niue'), ('CG', 'Congo'), ('TC', 'Turks and Caicos Islands'), ('PT', 'Portugal'), ('CH', 'Switzerland'), ('BD', 'Bangladesh'), ('AU', 'Australia'), ('QA', 'Qatar'), ('VG', 'Virgin Islands (British)'), ('BB', 'Barbados'), ('IM', 'Isle of Man'), ('SA', 'Saudi Arabia'), ('TK', 'Tokelau'), ('LK', 'Sri Lanka'), ('SE', 'Sweden'), ('MW', 'Malawi'), ('AT', 'Austria'), ('LA', "Lao People's Democratic Republic"), ('NL', 'Netherlands'), ('TD', 'Chad'), ('ZM', 'Zambia'), ('LU', 'Luxembourg'), ('BM', 'Bermuda'), ('GH', 'Ghana'), ('AI', 'Anguilla'), ('BI', 'Burundi'), ('EE', 'Estonia'), ('MY', 'Malaysia'), ('CF', 'Central African Republic'), ('FO', 'Faroe Islands'), ('IR', 'Iran (Islamic Republic of)'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BE', 'Belgium'), ('NP', 'Nepal'), ('HT', 'Haiti'), ('US', 'United States of America'), ('UZ', 'Uzbekistan'), ('CU', 'Cuba'), ('SS', 'South Sudan'), ('KH', 'Cambodia'), ('DO', 'Dominican Republic'), ('CK', 'Cook Islands'), ('BJ', 'Benin'), ('BN', 'Brunei Darussalam'), ('BL', 'Saint Barthélemy'), ('KZ', 'Kazakhstan'), ('WF', 'Wallis and Futuna'), ('FR', 'France'), ('PH', 'Philippines'), ('NG', 'Nigeria'), ('UY', 'Uruguay'), ('VA', 'Holy See'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('SB', 'Solomon Islands'), ('LR', 'Liberia'), ('TV', 'Tuvalu'), ('AR', 'Argentina'), ('TG', 'Togo'), ('NF', 'Norfolk Island'), ('EC', 'Ecuador'), ('JM', 'Jamaica'), ('RU', 'Russian Federation'), ('TM', 'Turkmenistan'), ('PK', 'Pakistan'), ('VE', 'Venezuela (Bolivarian Republic of)'), ('SD', 'Sudan'), ('TO', 'Tonga'), ('AX', 'Åland Islands'), ('KM', 'Comoros'), ('HR', 'Croatia'), ('FK', 'Falkland Islands  [Malvinas]'), ('CL', 'Chile'), ('GN', 'Guinea'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('AF', 'Afghanistan'), ('PN', 'Pitcairn'), ('SY', 'Syrian Arab Republic'), ('MV', 'Maldives'), ('BA', 'Bosnia and Herzegovina'), ('MH', 'Marshall Islands'), ('AQ', 'Antarctica'), ('SX', 'Sint Maarten (Dutch part)'), ('AG', 'Antigua and Barbuda'), ('OM', 'Oman'), ('VU', 'Vanuatu'), ('MC', 'Monaco'), ('KN', 'Saint Kitts and Nevis'), ('KY', 'Cayman Islands'), ('MQ', 'Martinique'), ('SI', 'Slovenia'), ('BG', 'Bulgaria'), ('MO', 'Macao'), ('GI', 'Gibraltar'), ('GP', 'Guadeloupe'), ('GS', 'South Georgia and the South Sandwich Islands'), ('GF', 'French Guiana'), ('CW', 'Curaçao'), ('DZ', 'Algeria'), ('PL', 'Poland'), ('YT', 'Mayotte'), ('RS', 'Serbia'), ('GU', 'Guam'), ('MN', 'Mongolia'), ('PG', 'Papua New Guinea'), ('ER', 'Eritrea'), ('DJ', 'Djibouti'), ('ML', 'Mali'), ('KI', 'Kiribati'), ('MG', 'Madagascar'), ('SR', 'Suriname'), ('IE', 'Ireland'), ('NA', 'Namibia'), ('IS', 'Iceland'), ('KE', 'Kenya'), ('LV', 'Latvia'), ('PA', 'Panama'), ('IN', 'India'), ('GA', 'Gabon'), ('PY', 'Paraguay'), ('NR', 'Nauru'), ('TW', 'Taiwan (Province of China)')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='price',
            field=django_prices.models.PriceField(currency='BGN', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='shippingmethodcity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingMethodCountry'),
        ),
    ]
