# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20160622_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, choices=[('', 'Any country'), ('BG', 'Bulgaria')], default='', max_length=2, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ShippingMethodCity',
            new_name='ShippingCity',
        ),
        migrations.AlterField(
            model_name='shippingcity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingCountry'),
        ),
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='country_code',
            field=models.CharField(blank=True, choices=[('', 'Any country'), ('BG', 'Bulgaria')], default='', max_length=2),
        ),
    ]
