# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20160703_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOffice',
            fields=[
                ('external_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('address_en', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('office_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('update_time', models.DateTimeField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingcity',
            name='id',
        ),
        migrations.AlterField(
            model_name='shippingcity',
            name='external_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='shippingoffice',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingCity'),
        ),
        migrations.AddField(
            model_name='shippingoffice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingCountry'),
        ),
    ]
