# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20160709_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='description_bg',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='description_en_us',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
