# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_auto_20160810_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='name_en_us',
            new_name='name_en',
        ),
    ]
