# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import sqlparse


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_auto_20160820_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcity',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunSQL('UPDATE shipping_shippingcity SET name_bg = name;'),
    ]
