# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_auto_20160824_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingoffice',
            name='address_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingoffice',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingcity',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingoffice',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingoffice',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunSQL('UPDATE shipping_shippingoffice SET name_bg = name;'),
        migrations.RunSQL('UPDATE shipping_shippingoffice SET address_bg = address;')
    ]
