# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_auto_20160824_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingcity',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='shippingoffice',
            options={'ordering': ('name',)},
        ),
    ]
