version: '2'

services:
  db:
    image: library/postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - saleor-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

volumes:
  saleor-db:
    driver: local
