# Generated by Django 2.2 on 2019-05-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128)),
                ('ttc_mfa_id_old', models.TextField(blank=True)),
                ('ttc_mfa_id_new', models.TextField(blank=True)),
                ('logo_picture', models.TextField(blank=True)),
                ('from_year', models.TextField(blank=True)),
                ('to_year', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_car', models.TextField(blank=True)),
                ('ttc_mod_id', models.TextField(blank=True)),
                ('logo_picture', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo_picture', models.TextField(blank=True)),
                ('automaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='autoparts.Automaker')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('type_car', models.TextField(blank=True)),
                ('body_type', models.TextField(blank=True)),
                ('of_the_year', models.DateTimeField(null=True)),
                ('up_to_year', models.DateTimeField(null=True)),
                ('kw', models.TextField(blank=True)),
                ('hp', models.TextField(blank=True)),
                ('engine_cc', models.TextField(blank=True)),
                ('ttc_typ_id', models.TextField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('technical_information', models.TextField(blank=True)),
                ('engine_codes', models.TextField(blank=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='autoparts.CarModel')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='autoparts.Series'),
        ),
    ]
