# Generated by Django 2.2 on 2019-05-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='engine_cc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
