# Generated by Django 2.2 on 2019-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0002_auto_20190506_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
