# Generated by Django 2.2 on 2019-05-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0003_partbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='partbrand',
            name='logo_picture',
            field=models.TextField(blank=True),
        ),
    ]
