# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-21 19:27
from __future__ import unicode_literals

from django.db import migrations

from saleor.userprofile.models import User


def init_date(apps, schema_editor):
    admin = User(email="admin@ap1.com", is_active=True, is_staff=True, is_superuser=True)
    admin.set_password("pass")
    admin.save()

    client = User(email="client@ap1.com", is_active=True, is_staff=False, is_superuser=False)
    client.set_password("pass")
    client.save()


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0005_auto_20160205_0651'),
    ]

    operations = [
        migrations.RunPython(init_date)
    ]
