# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20160709_0945'),
        ('userprofile', '0007_auto_20160710_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shipping.ShippingOffice', verbose_name='office'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ShippingCity', verbose_name='city'),
        ),
    ]
