# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20160711_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shipping.ShippingCity', verbose_name='city'),
        ),
    ]
