# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-16 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20160711_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='to_office',
            field=models.BooleanField(default=False),
        ),
    ]
