# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_address_to_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shipping.ShippingOffice', verbose_name='office'),
        ),
    ]
