# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20160717_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='phone number'),
        ),
    ]
