# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-30 18:29
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20160730_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, verbose_name='phone number'),
        ),
    ]
