# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20160730_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='to_office',
            field=models.BooleanField(default=False, verbose_name='To office'),
        ),
    ]
