# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20160622_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='group_id'),
        ),
    ]
