# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-17 18:59
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20160622_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=django_prices.models.PriceField(currency='BGN', decimal_places=2, default=1, max_digits=12, verbose_name='price'),
            preserve_default=False,
        ),
    ]
