# Generated by Django 2.2 on 2019-05-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0069_auto_20190225_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='bg', max_length=35),
        ),
    ]
